spring:
  profiles:
    group:
      "local" : "common-env, local-env, swagger"
      "dev" : "common-env, dev-env, swagger"
      "prod" : "common-env, prod-env"
    active: ${profile}
---
spring:
  config:
    activate:
      on-profile: "common-env"
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
      accept-empty-array-as-null-object: true
    date-format: yyyy-MM-dd'T'HH:mm:ssZ
    time-zone: Asia/Seoul

server:
  port: 8080

slack:
  url: https://hooks.slack.com/services/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
---
spring:
  config:
    activate:
      on-profile: "prod-env"

server-setting-values:
  is-production: true
  enable-scheduler: false
---
spring:
  config:
    activate:
      on-profile: "dev-env"

server-setting-values:
  is-production: false
  enable-scheduler: false
---
spring:
  config:
    activate:
      on-profile: "local-env"
server-setting-values:
  is-production: false
  enable-scheduler: false
